# This is a basic workflow to help you get started with Actions

name: PruebaPython

# Controls when the workflow will run
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "aprendiendo-github-actions" ]
  pull_request:
    branches: [ "aprendiendo-github-actions" ]
     # Triggers the workflow on push or pull request events but only for the "main" branch
 
  

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs: 
  Build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: setup python 3.10  #Nombre del 1er step
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      

      # Runs a single command using the runners shell
      - name: Correr Script #Nombre del 1er step
        run: python HolaMundo.py #Comando que se va ejecutar

     
